version: '3.8'

services:
  transcoder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamx-transcoder
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BACKEND_URL=${BACKEND_URL}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - CLOUDFRONT_DISTRIBUTION=${CLOUDFRONT_DISTRIBUTION}
    volumes:
      - ./tmp:/app/tmp
    depends_on:
      - redis
    networks:
      - streamx-network

  redis:
    image: redis:7-alpine
    container_name: streamx-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - streamx-network

volumes:
  redis_data:

networks:
  streamx-network:
    driver: bridge